### ISSUE TITLE
CoAP examples won't compile anymore with recent riot-os branches

### ISSUE THREAD

**Issue by richardklingler** [pyaiot/riot-firmwares#2]
Switching RIOT to "master" leaves to a compile error since sys/net/application_layer/coap has been renamed to "sys/net/application_layer/gcoap":

"/Library/Developer/CommandLineTools/usr/bin/make" -C /Users/Me/Develop/riot-firmwares/RIOT/sys/net/application_layer/gcoap
make: *** /Users/Me/Develop/riot-firmwares/RIOT/sys/net/application_layer/gcoap: No such file or directory.  Stop.
make[2]: *** [ALL--/Users/Me/Develop/riot-firmwares/RIOT/sys/net/application_layer/gcoap] Error 2
make[1]: *** [ALL--/Users/Me/Develop/riot-firmwares/RIOT/sys] Error 2

**Comment by aabadie** [comment]
Hi Richard,

Thanks for your interest in RIOT and Pyaiot :)

I just ran a few builds against the latest release (2017.10) of RIOT and master and everything builds fine.
I suspect you have old intermediate files from previous builds in your application directories. Can you just run a `make clean` before building the applications ?

**Comment by richardklingler** [comment]
Salue Alexandre

Make clean didn't help....had to do a fresh git clone, init submodules and inside RIOT a git checkout master...my sample multihop network runs again with latest software (o;

thanks and great examples btw (o;
richard
