### ISSUE TITLE
Wrong format for temperatures below zero

### ISSUE THREAD

**Issue by richardklingler** [pyaiot/riot-firmwares#4]
In coap_bme280.x  on line 47 and 96 the formatting is wrong...

As imple test with:

	int	temperature;

	for (temperature = 100; temperature > -2000; temperature = temperature - 10)
		printf("Temperature is: %d.%d\n", temperature / 100, (temperature % 100) /10);

Gives:

Temperature is: 1.0
Temperature is: 0.9
Temperature is: 0.8
Temperature is: 0.7
Temperature is: 0.6
Temperature is: 0.5
Temperature is: 0.4
Temperature is: 0.3
Temperature is: 0.2
Temperature is: 0.1
Temperature is: 0.0
Temperature is: 0.-1
Temperature is: 0.-2
Temperature is: 0.-3
Temperature is: 0.-4
Temperature is: 0.-5
Temperature is: 0.-6
Temperature is: 0.-7
Temperature is: 0.-8
Temperature is: 0.-9
Temperature is: -1.0
Temperature is: -1.-1
Temperature is: -1.-2
Temperature is: -1.-3

**Comment by richardklingler** [comment]
This would work correctly:

p += sprintf((char*)response, "%d.%d°C", temperature / 100, abs(temperature % 100) /10);

**Comment by aabadie** [comment]
Obviously, yes
